kind: pipline
name: Winsper-UserService

steps:
  - name: test
    image: maven
    volumes:
      - name: dependency
        path: /root/.m2
    # - name: configuration
    #   path: /drone/src/back-end/src/main/resources/application.yml
    commands:
      - mvn clean
      - mvn package -Dmaven.test.skip=true
      - echo "test and package zuul completed 🙂🙂🙂"

  - name: upload
    image: appleboy/drone-scp
    settings:
      host: 10.0.0.98
      username: root
      key:
        from_secret: private_key
      rm: true
      target: /Winsper/winsper-user
      source:
        - target/user-service-0.0.1-SNAPSHOT.jar
        - Dockerfile

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.98
      username: root
      key:
        from_secret: private_key
      script:
        - cd /root/test/drone-tmp/target
        - cp ../Dockerfile .
        - docker build -t deeell-test/winsper-user .



volumes:
  - name: dependency
    host:
      path: /root/.m2
