kind: pipline
name: Winsper-UserService

steps:
- name: test
  image: maven
  volumes:
  - name: dependency
    path: /root/.m2
# - name: configuration
#   path: /drone/src/back-end/src/main/resources/application.yml
  commands:
  - mvn clean
  - mvn package -Dmaven.test.skip=true
  - echo "test and package user-service completed 🙂🙂🙂"

- name: upload_master
  image: appleboy/drone-scp
  settings:
    host: 10.0.0.98
    username: root
    rm: true
    target: /Winsper/user-service
    source:
      - target/user-service-0.0.1-SNAPSHOT.jar
      - Dockerfile

- name: deploy_master
  image: appleboy/drone-ssh
  settings:
    host: 10.0.0.98
    username: root
    script:
      - cd /Winsper/user-service/target
      - cp ../Dockerfile .
      - docker build -t winsper-user-service .
      - docker rm -f winsper-user-service-c
      - docker run -d --name winsper-user-service-c --expose=7180 -p 7180:7180 -e "EUREKA_INSTANCE_IP-ADDRESS=10.0.0.98" -e "SERVER_PORT=7180" winsper-user-service

volumes:
- name: dependency
  host:
    path: /root/.m2
