kind: pipline
name: winsper-user

steps:
  - name: test
    image: maven
    volumes:
      - name: dependency
        path: /root/.m2
    # - name: configuration
    #   path: /drone/src/back-end/src/main/resources/application.yml
    commands:
      - mvn clean
      - mvn package -Dmaven.test.skip=true
      - echo "test and package user-service completed 🙂🙂🙂"

  - name: upload_master
    image: appleboy/drone-scp
    settings:
      host: 10.0.0.98
      username: root
      key:
        from_secret: private_key
      rm: true
      target: /Winsper/winsper-user
      source:
        - target/user-service-0.0.1-SNAPSHOT.jar
        - Dockerfile

  - name: make_image_and_copy
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.98
      username: root
      script:
        - cd /Winsper/winsper-user/target
        - cp ../Dockerfile .
        - docker build -t winsper-user .
        - docker save winsper-user>winsper-user.tar
        - scp winsper-user.tar root@10.0.0.106:/root/Winsper/winsper-user
        - scp winsper-user.tar root@10.0.0.39:/root/Winsper/winsper-user
        - scp winsper-user.tar root@10.0.0.99:/root/Winsper/winsper-user

  - name: deploy_slave1
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.106
      username: root
      script:
        - cd /Winsper/winsper-user
        - docker load -i winsper-user.tar
        - docker rm -f winsper-user-c
        - docker run -d --name winsper-user-c --expose=7180 -p 7180:7180 -e "EUREKA_INSTANCE_IP-ADDRESS=10.0.0.106" -e "SERVER_PORT=7180" winsper-user

  - name: deploy_slave2
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.39
      username: root
      script:
        - cd /Winsper/winsper-user
        - docker load -i winsper-user.tar
        - docker rm -f winsper-user-c
        - docker run -d --name winsper-user-c --expose=7180 -p 7180:7180 -e "EUREKA_INSTANCE_IP-ADDRESS=10.0.0.39" -e "SERVER_PORT=7180" winsper-user

  - name: deploy_slave3
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.99
      username: root
      script:
        - cd /Winsper/winsper-user
        - docker load -i winsper-user.tar
        - docker rm -f winsper-user-c
        - docker run -d --name winsper-user-c --expose=7180 -p 7180:7180 -e "EUREKA_INSTANCE_IP-ADDRESS=10.0.0.99" -e "SERVER_PORT=7180" winsper-user




volumes:
  - name: dependency
    host:
      path: /root/.m2
